# Dose in mg/kg
# Concentration in mg/ml
Medetomidine:
  default dose: 0.005
  doses:
    - 0.005
    - 0.01
    - 0.015
    - 0.02
    - 0.025
  concentration: 1
Methadone:
  default dose: 0.2
  doses:
    - 0.2
    - 0.3
  concentration: 10
Buprenorphine:
  dose: 0.02
  concentration: 0.3
Butorphanol:
  dose: 0.2
  concentration: 10
Atipam:
  dose: 0.025
  concentration: 5
Adrenaline:
  dose: 0.02
  concentration: 10
Lidocaine toxic dose:
  dose: 4
  concentration: 10
Onsior:
  dose: 2
  concentration: 20
Meloxicam:
  dose: 0.2
  concentration: 5
