# Dose in mg/kg
# Concentration in mg/ml
Medetomidine:
  default_dose: 0.005
  dose_options:
    - 0.005
    - 0.01
    - 0.015
    - 0.02
    - 0.025
  concentration: 1
Methadone:
  default_dose: 0.2
  dose_options:
    - 0.2
    - 0.3
  concentration: 10
Buprenorphine:
  default_dose: 0.02
  dose_options:
  concentration: 0.3
Butorphanol:
  default_dose: 0.2
  dose_options:
  concentration: 10
Atipam:
  default_dose: 0.025
  dose_options:
  concentration: 5
Adrenaline:
  default_dose: 0.02
  dose_options:
  concentration: 10
Lidocaine toxic dose:
  default_dose: 4
  dose_options:
  concentration: 10
Onsior:
  default_dose: 2
  dose_options:
  concentration: 20
Meloxicam:
  default_dose: 0.2
  dose_options:
  concentration: 5
